name: Main

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  main:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain v1.70.0 (MSRV)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.70.0

    - name: Install Rust toolchain nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: Check compilation
      run: |
        cargo +1.70.0 check

    - name: Run tests
      run: |
        cargo +1.70.0 test

    - name: Run doc-tests
      run: |
        cargo +nightly test\
        --doc
